ServerName: ""
Register:
  Blind: false
  Nausea: false
  TimeOut: 60
  Max: 2
Login:
  Blind: true
  Nausea: true
  TimeOut: 30
  MaxTries: 5
AntiBot: false
Pin: true
Updater:
  Check: true
  CheckTime: 10
  ChangeLog: false
  AutoUpdate: true
2FA: true
ClearChat: false
AccountsPerIp: 2
CheckNames: true
Servers:
  AuthLobby: authlobby
  MainLobby: lobby
FallBack:
  AuthLobby: fbauth
  MainLobby: fblobby
Lang: en_EN
AccountSys: File