###########################################################
#                                                         #
#   LockLogin source is a plugin under GSA GPL license    #
#           https://karmaconfigs.ml/license               #
#                                                         #
#                                                         #
#                   For more help                         #
#             go to: https://rb.gy/jlmjah                 #
#                                                         #
###########################################################

#This is used by 2fa
#and some plugin messages
ServerName: ""

#Registration options
# Blind -> Applies a blind potion
#          effect when the player
#          joins if he's not registered
#
# Nausea -> Applies a confusion effect
#           when the player joins if he's
#           not registered, util for anarchy
#           servers
#
# TimeOut -> The maximum time the player has
#            to perform the register
#
# Max -> The maximum amount of accounts allowed
#        TO REGISTER per IP
Register:
  Blind: false
  Nausea: false
  TimeOut: 60
  Max: 2

#Login options
# Blind -> Applies a blind potion
#          effect when the player
#          joins if he's not logged in
#
# Nausea -> Applies a confusion effect
#           when the player joins if he's
#           not logged in, util for anarchy
#           servers
#
# TimeOut -> The maximum time the player has
#            to perform the login
#
# MaxTries -> The maximum amount of password tries
#             the player has before getting kicked
Login:
  Blind: true
  Nausea: true
  TimeOut: 30
  MaxTries: 5

#Login/Register messages in chat
#interval, minimum is 5, maximum is
#the specified in Login/Register section
#( TimeOut time )
MessagesInterval:
  Registration: 5
  Logging: 5

#Captcha options
# Available options:
#   COMPLEX -> Requires to do /captcha <captcha> before
#             login or register
#   SIMPLE -> Requires to put the captcha during login
#            and register
#   DISABLED -> Completely disables this feature
#              ( Not recommended, use it at your own risk )
# TimeOut -> Set to 0 to disable
#
# Difficulty -> Captcha difficulty settings
#   Length -> Captcha code length ( min is 8, max is 16 )
#   Letters -> Include letters in the captcha
#   Strikethrough -> Strikethrough captcha settings
#     Enabled -> Enable strikethrough feature
#     Random -> Randomize the characters with strikethrough
#             effect
Captcha:
  Mode: "SIMPLE"
  TimeOut: 0
  Difficulty:
    Length: 8
    Letters: true
    Strikethrough:
      Enabled: true
      Random: true

#Encryption configuration
# Available types:
# "SHA512"
# "SHA256"
# "BCrypt"
# "Argon2i"
# "Argon2id"
Encryption:
  Passwords: "SHA512"
  Pins: "SHA512"

#Azuriom integration options
# Restrict -> Restrict new accounts to
#             azuriom registered accounts
#
# SemiPremium -> Try to use online player UUID
Azuriom:
  Restrict: false
  SemiPremium: false

#BurteForce options
# Tries -> The maximum amount of tries
#          the IP has to login per connection
#          (Per connection = Respecting Login's MaxTries)
#
# BlockTime -> The time (in minutes) the IP will
#              be blocked if tries get to 0
BruteForce:
  Tries: 3
  BlockTime: 30

#Protect the server against
#connections with the same
#name. ( THIS IS USELESS IN
# BUNGEECORD, AND WILL BE
# REMOVED IN A FUTURE )
AlreadyPlaying: false

#AntiBot is a feature that
#will try to keep bots away
#from your server by just checking
#if the connecting player has pinged
#the server (bots doesn't ping servers)
AntiBot: false

#Enable pin feature (This is not 2FA)
#LockLogin pin or LockLogin Pinner is
#an extra pin feature that adds an extra
#security layer to your players accounts
Pin: true

#Updater options
# Channel -> Update system channel;
#            Available channels:
#            - RELEASE
#            - RC | RELEASECANDIDATE | RELEASE_CANDIDATE
#            - SNAPSHOT
#
# Check -> Enable the update checker
#          if disabled, an unique check
#          will be performed on each server
#          start
#
# CheckTime -> The time (in minutes) before each
#              update check, the minimum is 5 and
#              the maximum is 86400 (1 day)
#
# ChangeLog -> Enable changelog displayer in each
#              new update found message
Updater:
  Channel: "RELEASE"
  Check: true
  CheckTime: 10

#Enable 2FA feature (using Google Authenticator)
#This adds and extra security layer to your
#players account, but since due Spigot API is
#bypasseable, you should enable PIN feature
#For help while using/scanning 2FA QR codes
#check these link:
#
# https://rb.gy/clq5ou
# https://rb.gy/ugciij
# This tutorial is on an iPhone
# but the process is the same
# on Android
2FA: true

#Enable clear chat feature, this
#option will clear ONLY CONNECTED
#PLAYER chat, there won't be a change
#for other players
ClearChat: false

#The maximum amount of accounts allowed
#TO BE IN THE SERVER per IP
AccountsPerIp: 2

#Toggle LockLogin name verifier when
#a player joins the server, using
#mojang's name rules:
#4 chars min, 16 max, only "_" allowed
CheckNames: true

#Server options
# getAuthLobby -> The server used by the
#              plugin to log players.
#              In that server, the player
#              will stay there until they
#              login/register
#
# getMainLobby -> The server used as lobby.
#              The player will be took here
#              after logging in/register
Servers:
  AuthLobby: authlobby
  MainLobby: lobby

#Fallback servers options
# ( A fallback server is a
#   secondary server used in
#   case some of the principals
#   goes down )
# getAuthLobby -> Fallback auth server, in case
#              the original goes down, this one
#              will be used, if the fallback one
#              goes down, the current server of the player
#              will be used ( That's why I recommend
#              to install LockLogin in all your bukkit
#              instances )
# getMainLobby -> Fallback lobby server, in case
#              the original goes down, this one
#              will be used, if the fallback one
#              goes down, the player won't be took
#              to any server
FallBack:
  AuthLobby: fbauth
  MainLobby: fblobby

#Plugin language
#For more info please visit:
# https://rb.gy/jlmjah
Lang: en_EN

#Account storage system
#For more info please visit:
# https://rb.gy/jlmjah
AccountSys: File